CC=g++
CFLAGS=-c -Wall
all: hw2_prob1 hw2_prob2 hw2_prob3

hw2_prob1: hw2_prob1.cpp
	$(CC) -o hw2_prob1 hw2_prob1.cpp
hw2_prob2: hw2_prob2.cpp
	$(CC) -o hw2_prob2 hw2_prob2.cpp 
hw2_prob3: hw2_prob3.cpp
	$(CC) -o hw2_prob3 hw2_prob3.cpp 
clean:
	rm -f *.o
