CC=g++
CFLAGS=-c -Wall
all: rubydice1 rubydice2 chain

rubydice1: rubydice1.cpp
	$(CC) -o rubydice1 rubydice1.cpp
rubydice2: rubydice2.cpp
	$(CC) -o rubydice2 rubydice2.cpp 
chain: chain.cpp
	$(CC) -o chain chain.cpp 
clean:
	rm -f *.o
